version: "2"
services:
  app:
    image: tkaaad97/uievents-ci:ghc-8.6.5
    working_dir: $PWD
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - "$PWD:$PWD"
      - .stack:/root/.stack
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
