name:                uievents-GLFW-b
version:             0.3.0
license:             BSD3

dependencies:
- base >= 4.10 && < 5
- chronos >=1.1 && <1.2
- uievents >=0.3.0 && <0.4
- GLFW-b >= 3.2.1 && <3.4

ghc-options:
- -O2
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -Wtabs

library:
  source-dirs: src

executables:
  uievents-GLFW-b-example:
    main:                Main.hs
    source-dirs:
    - ../example-common
    - example
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gl
    - uievents-GLFW-b
    - linear
    - text
    - transformers
    - vector
