name:                uievents-GLFW-b
version:             0.4.0
license:             BSD3

flags:
  example:
    manual: true
    default: false

dependencies:
- base >= 4.10 && < 5
- chronos >=1.1 && <1.2
- linear >=1.20.8 && <1.22
- uievents >=0.4.0 && <0.5
- GLFW-b >= 3.3.0 && <3.4
- bindings-GLFW >= 3.3.0 && <3.4

ghc-options:
- -O2
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -Wtabs

library:
  source-dirs: src

executables:
  uievents-GLFW-b-example:
    when:
      - condition: !flag(example)
        buildable: false
    main:                Main.hs
    source-dirs:
    - ../example-common
    - example
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bytestring
    - containers
    - gl
    - linear
    - string-qq
    - text
    - transformers
    - uievents-GLFW-b
    - vector
