name:                uievents-sdl2
version:             0.2.0
license:             BSD3

dependencies:
- base >= 4.10 && < 5
- uievents >=0.2.0 && <0.3
- sdl2 >=2.4.0.1 && <2.6

ghc-options:
- -O2
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -Wtabs

library:
  source-dirs: src

executables:
  example:
    main:                Main.hs
    source-dirs:
    - example
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - uievents-sdl2
    - linear
    - text
    - transformers
    - StateVar
    - vector
