name:                uievents
version:             0.3.0
license:             BSD3

dependencies:
- base >= 4.10 && < 5
- linear >=1.20.8 && <1.22
- mtl >=2.2.2 && <2.3
- hashable >=1.2.7.0 && <1.4
- transformers >=0.3.0.0 && <0.6
- vector >=0.12.0.1 && <0.13
- vector-algorithms >=0.7.0.1 && <0.9

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -Wtabs

library:
  source-dirs: src

tests:
  uievents-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - uievents
    - hspec
